### PR TITLE
Port to ppx-based preprocessing

### PR DESCRIPTION
**Pull request by glondu**
Disclaimer: this is my first ppx-based thing. I don't pretend to follow all best practices. I did this port to learn. It depends on ocaml-migrate-parsetree.

This should fix https://github.com/ygrek/extunix/issues/32.

### CODE REVIEW

**Comment by glondu** [comment]
The AppVeyor build revealed that externals for unsupported functions that are inside submodules:

- caml_extunix_closelog
- caml_extunix_openlog
- caml_extunix_poll_constants
- caml_extunix_setlogmask
- caml_extunix_syslog

are not properly rewritten. I'll try to fix that next week.

**Comment by glondu** [comment]
> The AppVeyor build revealed that externals for unsupported functions that are inside submodules

I've fixed that now, and the AppVeyor build succeeds.

On Travis, I've seen that OCaml 4.02 is not supported any more. Is that important?

**Comment by glondu** [comment]
I (sort of) fixed the issue with OCaml 4.02. The remaining failures on Travis CI seem random and unrelated to extunix itself.

**Comment by XVilka** [comment]
Any updates on this one?

**Comment by ygrek** [comment]
@glondu huge thanks for this! Sorry for taking long to merge

**Pull request merged**
